name: Cross-Platform PyInstaller Build

on:
  push:
    tags:
      - 'v*'  # Triggers on tag creation

jobs:
  build:
    name: Build and Bundle Executable
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # Download FFmpeg based on platform
      - name: Download FFmpeg (Linux & macOS)
        if: runner.os != 'Windows'
        run: |
          mkdir -p ffmpeg
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            curl -L https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz
            tar -xf ffmpeg.tar.xz --strip-components=1 -C ffmpeg
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            curl -L https://evermeet.cx/ffmpeg/ffmpeg -o ffmpeg/ffmpeg
            chmod +x ffmpeg/ffmpeg
          fi

      - name: Download FFmpeg (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir ffmpeg
          curl -L https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip -o ffmpeg.zip
          tar -xf ffmpeg.zip -C ffmpeg
        shell: cmd

      # Bundle application with PyInstaller
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --add-binary "ffmpeg/ffmpeg:." main.py

      # Archive the build artifact
      - name: Archive executable
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-build
          path: dist/main  # Adjust this path to your app's output name

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Create a release and attach artifacts
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
